from src.exceptions import AppBaseException


class CloudStorageException(AppBaseException): ...


class CloudStorageNotImplementedException(CloudStorageException): ...


class CloudStorageUnsupportedType(CloudStorageException): ...


class CloudStorageImportError(CloudStorageException): ...