from src.exception import AppBaseException

class VectorStoreException(AppBaseException): ...

class VectorStoreAuthError(VectorStoreException): ...

class VectorStoreNotFoundError(VectorStoreException): ...

class VectorStorePermissionError(VectorStoreException): ...

class VectorStoreServiceError(VectorStoreException): ...

class VectorStoreInternalError(VectorStoreException): ...

class VectorStoreNotImplementedError(VectorStoreException): ...

class VectorStoreIndexAlreadyExist(VectorStoreException): ...

class VectorStoreImportError(VectorStoreException): ...